# Generated by Django 4.2.7 on 2023-12-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_register',
            old_name='email',
            new_name='phone',
        ),
    ]
