# Generated by Django 4.2.7 on 2023-12-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop_app', '0002_rename_email_user_register_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
